### ISSUE TITLE
bug: drawtext and notifications stacking

### ISSUE THREAD

**Issue by menkzy** [qbcore-framework/qb-garbagejob#13]
As you do more jobs, the notifications and 3dtext stack. 
Notifications: https://i.imgur.com/mLcXh0r.png
3d Text : https://i.imgur.com/ouJ6yjb.png | https://i.imgur.com/Ofzan3G.png | https://i.imgur.com/SJANvPk.png

**Comment by roobr** [comment]
I have been able to replicate this issue

**Comment by roobr** [comment]
if you park your truck right next to the garbage bin it will do both pickup and place aswell

**Comment by IdrisDose** [comment]
Thanks I'll look into this.

**Comment by roobr** [comment]
Seems to happen after the first delivery. The first one has no issues with text or clicking e

On the second one if you click e once and are close enough it will deliver both. but not on the first one
