### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by redfe4r** [qbcore-framework/qb-garbagejob#37]
please add clothings in the config and into the script , so we can put custom clothes for the job when you go on duty!

**Comment by i-kulgu** [comment]
> please add clothings in the config and into the script , so we can put custom clothes for the job when you go on duty!

This can be done from qb-clothing.
You can open a new clothingroom inside Config.ClothingRooms and add the outfits to Config.Outfits:

![image](https://user-images.githubusercontent.com/29943243/186141751-0f607638-1be4-47f6-b782-79d1bf14c55b.png)
