### ISSUE TITLE
[BUG] Cant change the garbage truck in config.lua

### ISSUE THREAD

**Issue by brvieira8** [qbcore-framework/qb-garbagejob#42]
**Describe the bug**
Config Vehicles will not change the garbage truck

**To Reproduce**

**Comment by Mrx291983** [comment]
I solved this by just changing the config to:

Config.Vehicles = "trash2"

and in the client.lua change line 418 from:

end, 'trash2', coords, true)
to
end, Config.Vehicles, coords, true)

**Comment by tom-osborne** [comment]
Fixed in #45
