### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Luckyyang24** [qbcore-framework/qb-garbagejob#51]
Did a fresh install today and testing out this job as it doesn't appear the garbage truck when I request a route.  It just takes $250 away from my account and that's it.  I'm running the latest version of it as well.

**Comment by singh-manavv** [comment]
Do you get any errors in the console , if so please share a screenshot preview .

**Comment by Luckyyang24** [comment]
there's no error on console/txadmin

**Comment by Luckyyang24** [comment]
> Do you get any errors in the console , if so please share a screenshot preview .

there's no error on console/txadmin

**Comment by singh-manavv** [comment]
how do i reproduce the issue ?

**Comment by Luckyyang24** [comment]
> how do i reproduce the issue ?

Ahh....i don't know,  Just did a fresh install, grab the job from city hall then went to interact with the npc to start a route job but it just take my money and doesn't summon a garbage truck like it did with the older version.  I had a older version before and that one work fine.

**Comment by nutter887** [comment]
Me too I don't know why it's not have error in cmd but when i call truck it's not spawn.

**Comment by Luckyyang24** [comment]
Any news on this?

**Comment by tom-osborne** [comment]
@Luckyyang24 Make sure you have your `qb-core` up to date. It needs to include the server sided vehicle spawn function. This can be seen here: https://github.com/qbcore-framework/qb-core/blob/main/server/functions.lua#L173

If you don't have this, the vehicle will not spawn.

**Comment by tom-osborne** [comment]
> ![image](https://user-images.githubusercontent.com/35836274/191219217-042afafd-cfc1-4d5f-b57c-685838d370c0.png)
> 
> here is the error, i have try tostring, dont work same error `if not IsAnyVehicleNearPoint(vector3(tostring(v.x),tostring(v.y),tostring(v.z)), 2.5) then`

For this error, make sure you have not edited anything in the config.lua. If you have, it is likely there is a mistake somewhere.

**Comment by Luckyyang24** [comment]
> @Luckyyang24 Make sure you have your `qb-core` up to date. It needs to include the server sided vehicle spawn function. This can be seen here: https://github.com/qbcore-framework/qb-core/blob/main/server/functions.lua#L173
> 
> If you don't have this, the vehicle will not spawn.

My core is up to date.  It work fine when I add in the old qb-garabagejob, just this new one.  Don't know if there's any miss spelling anywhere.

**Comment by tom-osborne** [comment]
It works for me on a fresh server build. Tested yesterday. Vehicle spawns fine and player get's keys.
It would be good if you could do some debugging. Work out where the issue is occurring on your server. 
Is it perhaps something linked to the parking space being occupied by an NPC vehicle? 

If you could provide further information of a specific issue, we can take a look at the code and fix it.

**Comment by cheatchansovoth** [comment]
i did a fresh install today, there is an issue vehicle is locked even the player has the key

**Comment by tom-osborne** [comment]
You can unlock it though right?

**Comment by cheatchansovoth** [comment]
yes i could not unlock  but i already solved it issues.First issue, the trash car is locked and another issue is sth wrong with SetGarbageRoute. If i set the UseTarget == true i cant drive the car.Third issue, it wont give the money back when i return the car.

**Comment by ItzExotical** [comment]
For anyone having "issues" with the truck being locked, use the command `/togglelocks`. That fixed it for me.

**Comment by midz8** [comment]
Same issue with the truck not spawning. No errors aswell. I have the new qbcore aswell and the new grabage job
