### ISSUE TITLE
Since latest build you dont teleport into truck after requesting a truck![BUG]

### ISSUE THREAD

**Issue by Revline-RP** [qbcore-framework/qb-garbagejob#52]
You dont spawn inside truck after requesting a truck! Truck does spawn but you can't enter it! No errors in console nor serverside

**Comment by alfiswielki** [comment]
I have the same ... car locked...

**Comment by ThatsJohnny** [comment]
I can confirm, when requesting the mission it spawns the truck but locks you complete out.
How to fix?
The bus driver job works perfect you spawn bus and you get into it and get keys
Make something similar to garbagejob and its perfect!

**Comment by CptNoHand** [comment]
Same

**Comment by tom-osborne** [comment]
To make it warp the player into the vehicle, you can set the following line from `false` to `true`
https://github.com/qbcore-framework/qb-garbagejob/blob/main/client/main.lua#L470
```lua
end, Config.Vehicle, v, false)
```
Change to:
```lua
end, Config.Vehicle, v, true)
```
