### ISSUE TITLE
Not getting keys on starting job[BUG]

### ISSUE THREAD

**Issue by gigitygamer** [qbcore-framework/qb-garbagejob#58]
When you click get a route it spawns truck but does not give you the keys

Do a fresh install of QB-core server from Tx admin in zap hosting

Get in the truck and go to the first stop

**Screenshots**
***The Doors are locked

**Questions (please complete the following information):**
 - When you last updated: month ago
 - Are you using custom resource? which ones? qb-target
 - Have you renamed `qb-` to something custom? no

**Additional context**

**Comment by ShomyTKD** [comment]
I can confirm this, anyone got fix yet?

**Comment by CoolHandDuke** [comment]
Having same issue.

**Comment by Aercascade** [comment]
> I can confirm this, anyone got fix yet?

I went looking through the code, (please be aware I am very much a newbie and only really do python stuff.)
but from what I can read through QB documentation Garbagejobs has the following:

                            SetVehicleDoorsLocked(veh, 2)

see details below:
    CARLOCK_NONE = 0,
    CARLOCK_UNLOCKED = 1,
    CARLOCK_LOCKED = 2,
    CARLOCK_LOCKOUT_PLAYER_ONLY = 3,
    CARLOCK_LOCKED_PLAYER_INSIDE = 4,
    CARLOCK_LOCKED_INITIALLY = 5,
    CARLOCK_FORCE_SHUT_DOORS = 6,
    CARLOCK_LOCKED_BUT_CAN_BE_DAMAGED = 7

So you have 2 options, you can remove the entry completely or modify the value "2" to "1"

Alternatively just use what I have done, and replace the code from line 444 to 488
This modified code also includes the line "TaskWarpPedIntoVehicle(PlayerPedId(), veh, -1)" so that you are teleported into the garbage truck when it spawns like other jobs but you can remove this if you would like the player to enter the vehicle themselves.

```
RegisterNetEvent('qb-garbagejob:client:RequestRoute', function()
    if garbageVehicle then continueworking = true TriggerServerEvent('garbagejob:server:PayShift', continueworking) end
    QBCore.Functions.TriggerCallback('garbagejob:server:NewShift', function(shouldContinue, firstStop, totalBags)
        if shouldContinue then
            if not garbageVehicle then
                local occupied = false
                for _,v in pairs(Config.Locations["vehicle"].coords) do
                    if not IsAnyVehicleNearPoint(vector3(v.x,v.y,v.z), 2.5) then
                        QBCore.Functions.TriggerCallback('QBCore:Server:SpawnVehicle', function(netId)
                            local veh = NetToVeh(netId)
                            SetVehicleEngineOn(veh, false, true)
                            garbageVehicle = veh
                            SetVehicleNumberPlateText(veh, "QB-" .. tostring(math.random(1000, 9999)))
                            SetEntityHeading(veh, v.w)
                            exports['LegacyFuel']:SetFuel(veh, 100.0)
                            SetVehicleFixed(veh)
                            SetEntityAsMissionEntity(veh, true, true)
     			    TaskWarpPedIntoVehicle(PlayerPedId(), veh, -1)
                            currentStop = firstStop
                            currentStopNum = 1
                            amountOfBags = totalBags
                            SetGarbageRoute()
                            TriggerEvent("vehiclekeys:client:SetOwner", QBCore.Functions.GetPlate(veh))
                            QBCore.Functions.Notify(Lang:t("info.deposit_paid", { value = Config.TruckPrice }))
                            QBCore.Functions.Notify(Lang:t("info.started"))
                            TriggerServerEvent("qb-garbagejob:server:payDeposit")
                        end, Config.Vehicle, v, false)
                        return
                    else
                        occupied = true
                    end
                end
                if occupied then
                    QBCore.Functions.Notify(Lang:t("error.all_occupied"))
                end
            end
            currentStop = firstStop
            currentStopNum = 1
            amountOfBags = totalBags
            SetGarbageRoute()
        else
            QBCore.Functions.Notify(Lang:t("info.not_enough", { value = Config.TruckPrice }))
        end
    end, continueworking)
end)
```

Hope this helps! :)
