### ISSUE TITLE
Did not get keys from garbage job [BUG]

### ISSUE THREAD

**Issue by marathivikya** [qbcore-framework/qb-garbagejob#62]
**Describe the bug**
When i try to request route vehicle spawn but i can not get in because i dont get any keys

**To Reproduce**
1. Go to 'Garbage Job'
2. Target and Click on 'Ped and Request Route'
3. See error in console

**Expected behavior**
Get keys of vehicle.

**Screenshots**
![image](https://user-images.githubusercontent.com/52385474/232203106-7e426130-5f88-4d6a-a85f-6c9ec6ea1b29.png)

**Questions (please complete the following information):**
 - When you last updated: this month
 - Are you using custom resource? which ones? zdiscord, ps-fuel
 - Have you renamed `qb-` to something custom? No

**Comment by AhmedMoustafaApps** [comment]
> **Describe the bug** When i try to request route vehicle spawn but i can not get in because i dont get any keys
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'Garbage Job'
> 2. Target and Click on 'Ped and Request Route'
> 3. See error in console
> 
> **Expected behavior** Get keys of vehicle.
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/52385474/232203106-7e426130-5f88-4d6a-a85f-6c9ec6ea1b29.png)
> 
> **Questions (please complete the following information):**
> 
> * When you last updated: this month
> * Are you using custom resource? which ones? zdiscord, ps-fuel
> * Have you renamed `qb-` to something custom? No

hello please update the core
