### ISSUE TITLE
[BUG] When i spawn the trash truck it is locked and we can not get into it ?

### ISSUE THREAD

**Issue by OgRyder77** [qbcore-framework/qb-garbagejob#65]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? [e.g. yes/no]

**Additional context**

**Comment by DavidJ0707** [comment]
I have the same issue, other jobs with similar mechanics work fine.

**Comment by CapnDeath82** [comment]
> I have the same issue, other jobs with similar mechanics work fine.

Try hitting the L key once by the truck.

**Comment by rody05** [comment]
You need to unlock the truck by pressing 'L' key

**Comment by WolfpackChloe** [comment]
> **Describe the bug** A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Use this item '....' (item's name from shared.lua if applicable)
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Questions (please complete the following information):**
> 
> * When you last updated: [e.g. last week]
> * Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
> * Have you renamed `qb-` to something custom? [e.g. yes/no]
> 
> **Additional context** Add any other context about the problem here.

Go to CLIENT, then MAIN.LUA and look for line 461 and set this to 0
<img width="415" alt="Screenshot 2023-12-27 011138" src="https://github.com/qbcore-framework/qb-garbagejob/assets/58238399/0535db4c-b810-43bc-b9cd-6ba5cb588925">

**Comment by JamieT0001** [comment]
#67 will commit suggested change above
